### ISSUE TITLE
Need Resize as well as draggable on Angular and Bootstrap Web pages 

### ISSUE THREAD

**Issue by ArunRK-Finsurge** [dmytro-parfenov/ngx-drag-resize#1]
I can't drag and drop  on bootstrap grid property I need a clarification can you give me an example to run that method

**Comment by dmytro-parfenov** [comment]
> I can't drag and drop  on bootstrap grid property I need a clarification can you give me an example to run that method

Can you give me your example? html and styles.

**Comment by dmytro-parfenov** [comment]
@ArunRK-Finsurge closed until you provide an example
