### ISSUE TITLE
Get the element's position relative to the boundary when it is being dragged

### ISSUE THREAD

**Issue by airdgo** [dmytro-parfenov/ngx-drag-resize#4]
At the moment, when an element is dragged the ngxDragged event emits an NgxDrag object which contains the native element and the object position in the viewport. 

Is there any way to get the element's relative position to the boundary?

**Comment by dmytro-parfenov** [comment]
> At the moment, when an element is dragged the ngxDragged event emits an NgxDrag object which contains the native element and the object position in the viewport. 
> 
> 
> 
> Is there any way to get the element's relative position to the boundary?

Hi! Thank you for your answer. I will check it soon and let you know.

**Comment by airdgo** [comment]
Hi, did you have a chance to look on the issue?

**Comment by dmytro-parfenov** [comment]
> Hi, did you have a chance to look on the issue?

Sorry for the late reply. It is justified by the fact of war in Ukraine. I didn't have enough time to process you request. 😥
But now I am ready to answer. 😉

After investigation I noticed that [changes](https://github.com/dmytro-parfenov/ngx-drag-resize/pull/5) you have requested aren't necessary. It just adds [redundant property](https://github.com/dmytro-parfenov/ngx-drag-resize/blob/07e3bc83f4cccf18ee8c4ecd6df9a696d7b974f6/projects/ngx-drag-resize/src/lib/drag/drag.ts#L5) to the `ngxDragged` event that can be calculated by yourself if needed.

Here is an example of retrieving element's relative position to the boundary with APIs available at the moment.

`app.component.ts`

```
import {Component, ElementRef, ViewChild} from '@angular/core';
import {NgxDrag} from 'ngx-drag-resize';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  /**
   * Draggable element's boundary
   *
   * @private
   */
  @ViewChild('dragArea') private readonly dragAreaRef: ElementRef<HTMLDivElement> | null = null;

  onDrag({top, right, bottom, left}: NgxDrag): void {
    const dragBoundaryClientRect = this.dragAreaRef?.nativeElement.getBoundingClientRect();

    if (!dragBoundaryClientRect) {
      return;
    }

    /**
     * Relative position of draggable element to its boundary
     */
    const position = {
      top: top - dragBoundaryClientRect.top,
      right: dragBoundaryClientRect.right - right,
      bottom: dragBoundaryClientRect.bottom - bottom,
      left: left - dragBoundaryClientRect.left
    };
  }
}
```

`app.component.html`

```
<section #dragArea>
  <div ngxDrag
       (ngxDragged)="onDrag($event)"
       [ngxDragBoundary]="dragArea"></div>
</section>
```

**Comment by dmytro-parfenov** [comment]
closed due to https://github.com/dmytro-parfenov/ngx-drag-resize/issues/4#issuecomment-1712836161
