### ISSUE TITLE
Border style affects resize operations

### ISSUE THREAD

**Issue by Pabo77a** [dmytro-parfenov/ngx-drag-resize#8]
Setting the border style of the drag / resize boundary area will make the the resizing of left and top borders fail.
You can easily verify this by adding a border style in the demo app:

.area {
  position: relative;
  height: 200px;
  width: 100%;
  **border-style:dotted;**
  border-radius: 3px;
  background: rgba(211, 211, 211, 0.25);

  &.large {
    height: 500px;
  }
}

**Comment by dmytro-parfenov** [comment]
> border-style:dotted;

I've checked it. Everything works as expected.

https://github.com/user-attachments/assets/35196e30-113b-48f4-823e-5531eaefbad3

Please, try using the latest library version `1.0.3` and provide more specific details if you still have an issue.

**Comment by dmytro-parfenov** [comment]
> Setting the border style of the drag / resize boundary area will make the the resizing of left and top borders fail. You can easily verify this by adding a border style in the demo app:
> 
> .area { position: relative; height: 200px; width: 100%; **border-style:dotted;** border-radius: 3px; background: rgba(211, 211, 211, 0.25);
> 
> &.large { height: 500px; } }

Hm, that's strange 🤔.
But you can just wrap the boundary into additional container with styled border. It will work as expected.

https://github.com/user-attachments/assets/3245d03e-885a-4083-a8c1-2c58b6e1eced
